name: Python Syntax Check and Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 src/ --max-line-length=200
          
      - name: Build Docker container
        run: |
          docker build -t auto-scaling-script .

      - name: Run Docker container
        run: |
          docker run --rm auto-scaling-script
